### ISSUE TITLE
error messages

### ISSUE THREAD

**Issue by morbidCode** [kuyaalvin/hr-amasi#1]
add_project.blade.php, edit_project.blade.php, view_projects.blade.php and view_positions.blade.php do not have display for all errors.

- [x] add error messages element and populate error messages during normal http requests @kuyaalvin
Code for add_project.blade.php and edit_project.blade.php
`@foreach ($errors->all() as $error)`
`{{ $error }}`
`@endforach`
- [x] add jquery to populate error messages in case of ajax requests @morbidCode

**Comment by kuyaalvin** [comment]
- Added error messages for add_project.blade.php and edit_project.blade.php

- removed jquery for error messages
