### ISSUE TITLE
List Employee Added Features

### ISSUE THREAD

**Issue by kuyaalvin** [kuyaalvin/hr-amasi#3]
Add the following features for View Employee :

-Filter of Lists:

- [ ] Add check boxes per field and submit button for list  - @morbidCode 
- [ ] Add appropriate design changes for check boxes and button - @kuyaalvin

-Search bar for Lists:

- [x] Decide what kind of user experience for search bar - @morbidCode @kuyaalvin

**Comment by morbidCode** [comment]
Checkboxes are now replaced by textboxes. All completed.
